server:
   port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGatewayService
 cloud:
     gateway:
       routes:
       - id: PlayListService
         uri: http://localhost:8082/
         predicates:
         - Path=/api/v1/findAllplaylists/**

       - id: AlbumService
         uri: http://localhost:8081/
         predicates:
         - Path=/api/v1/findallalbums/** 
                
       - id: AdminContactService
         uri: http://localhost:8084/
         predicates:
         - Path=/api/v1/findAllContacts/**
       